name: BOSON
email: suda1527403057@163.com
author: BOSON
url: https://bosoncode.github.io/
### baseurl修改为项目名，如果项目是'***.github.io'，则设置为空''
baseurl: "" 
resume_site: 个人简历网站
github: "https://github.com/BOSONCODE"
github_username: BOSONCODE 
FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : 多说账户
    disqus :
        short_name : Disqus账户
permalink:    none
excerpt_separator: ""
highlighter: rouge
